#!/usr/bin/env python3
"""Интерактивный wizard для настройки mcp-advisor."""

import asyncio
import os
from pathlib import Path

import questionary
from questionary import Style
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn

# Путь к корню проекта
PROJECT_ROOT = Path(__file__).parent.parent.parent
ENV_FILE = PROJECT_ROOT / ".env"

console = Console()

# Кастомный стиль для questionary (минималистичный, без цветного фона)
WIZARD_STYLE = Style(
    [
        ("qmark", "fg:cyan bold"),
        ("question", "bold"),
        ("answer", "fg:cyan"),
        ("pointer", "fg:cyan bold"),
        ("highlighted", "fg:cyan bold noreverse"),
        ("selected", "fg:cyan noreverse"),
        ("separator", "fg:cyan"),
        ("instruction", "fg:gray"),
        ("checkbox-selected", "fg:cyan"),
    ]
)

# Информация о провайдерах
PROVIDER_INFO = {
    "gemini": {
        "name": "Google Gemini",
        "env_key": "GEMINI_API_KEY",
        "url": "https://aistudio.google.com/apikey",
        "test_model": "gemini/gemini-2.0-flash",
        "models": ["gemini/gemini-2.0-flash", "gemini/gemini-2.5-pro-preview-06-05"],
    },
    "openai": {
        "name": "OpenAI",
        "env_key": "OPENAI_API_KEY",
        "url": "https://platform.openai.com/api-keys",
        "test_model": "openai/gpt-4o-mini",
        "models": ["openai/gpt-4o-mini", "openai/gpt-4o", "openai/o1-mini"],
    },
    "anthropic": {
        "name": "Anthropic",
        "env_key": "ANTHROPIC_API_KEY",
        "url": "https://console.anthropic.com/settings/keys",
        "test_model": "anthropic/claude-3-5-haiku-20241022",
        "models": [
            "anthropic/claude-3-5-haiku-20241022",
            "anthropic/claude-sonnet-4-20250514",
        ],
    },
    "deepseek": {
        "name": "DeepSeek",
        "env_key": "DEEPSEEK_API_KEY",
        "url": "https://platform.deepseek.com/api_keys",
        "test_model": "deepseek/deepseek-chat",
        "models": ["deepseek/deepseek-chat", "deepseek/deepseek-reasoner"],
    },
    "groq": {
        "name": "Groq",
        "env_key": "GROQ_API_KEY",
        "url": "https://console.groq.com/keys",
        "test_model": "groq/llama-3.3-70b-versatile",
        "models": ["groq/llama-3.3-70b-versatile", "groq/mixtral-8x7b-32768"],
    },
    "openrouter": {
        "name": "OpenRouter",
        "env_key": "OPENROUTER_API_KEY",
        "url": "https://openrouter.ai/keys",
        "test_model": "openrouter/google/gemini-2.0-flash-001",
        "models": [
            "openrouter/google/gemini-2.0-flash-001",
            "openrouter/anthropic/claude-3.5-sonnet",
        ],
    },
    "ollama": {
        "name": "Ollama (локальный)",
        "env_key": "OLLAMA_HOST",
        "url": "https://ollama.ai/download",
        "test_model": "ollama/llama3.2",
        "models": ["ollama/llama3.2", "ollama/mistral"],
        "default_value": "http://localhost:11434",
    },
    "ollama-cloud": {
        "name": "Ollama Cloud",
        "env_key": "OLLAMA_API_KEY",
        "url": "https://ollama.com",
        "test_model": "ollama-cloud/gpt-oss:120b-cloud",
        "models": ["ollama-cloud/gpt-oss:120b-cloud"],
    },
}


def load_existing_env() -> dict[str, str]:
    """Загружает существующие переменные из .env файла."""
    env_vars = {}
    if ENV_FILE.exists():
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip().strip('"').strip("'")
    return env_vars


def save_env(env_vars: dict[str, str]) -> None:
    """Сохраняет переменные в .env файл."""
    lines = []
    lines.append("# MCP Advisor Configuration")
    lines.append("# Generated by mcp-advisor setup\n")

    # Группируем переменные
    for key, value in sorted(env_vars.items()):
        if value:
            lines.append(f"{key}={value}")

    with open(ENV_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")


async def test_connection(provider: str, api_key: str) -> tuple[bool, str]:
    """Тестирует подключение к провайдеру."""
    from litellm import acompletion

    info = PROVIDER_INFO.get(provider, {})
    test_model = info.get("test_model")

    if not test_model:
        return False, "Неизвестный провайдер"

    # Устанавливаем переменную окружения для теста
    env_key = info["env_key"]
    os.environ[env_key] = api_key

    # Дополнительные переменные окружения
    if "extra_env" in info:
        for k, v in info["extra_env"].items():
            os.environ[k] = v

    try:
        kwargs = {"model": test_model, "max_tokens": 5}

        # Ollama Cloud требует особой настройки
        if provider == "ollama-cloud":
            kwargs["model"] = test_model.replace("ollama-cloud/", "openai/")
            kwargs["api_base"] = os.getenv(
                "OLLAMA_CLOUD_BASE_URL", "https://ollama.com/v1"
            )
            kwargs["api_key"] = api_key

        await acompletion(messages=[{"role": "user", "content": "Hi"}], **kwargs)
        return True, "OK"
    except Exception as e:
        error_msg = str(e)
        if "401" in error_msg or "Unauthorized" in error_msg:
            return False, "Неверный API ключ"
        if "429" in error_msg:
            return False, "Превышен лимит запросов"
        if "Connection" in error_msg or "timeout" in error_msg.lower():
            return False, "Ошибка подключения"
        return False, str(e)[:50]


async def test_model(model: str) -> tuple[bool, str]:
    """Тестирует доступность конкретной модели."""
    from litellm import acompletion

    if "/" not in model:
        return False, "Формат: provider/model"

    provider = model.split("/")[0]

    # Ollama Cloud требует особой настройки
    try:
        kwargs = {"model": model, "max_tokens": 5}

        if provider == "ollama-cloud":
            kwargs["model"] = model.replace("ollama-cloud/", "openai/")
            kwargs["api_base"] = os.getenv(
                "OLLAMA_CLOUD_BASE_URL", "https://ollama.com/v1"
            )
            kwargs["api_key"] = os.getenv("OLLAMA_API_KEY")

        await acompletion(messages=[{"role": "user", "content": "Hi"}], **kwargs)
        return True, "OK"
    except Exception as e:
        error_msg = str(e)
        if "404" in error_msg or "not found" in error_msg.lower():
            return False, "Модель не найдена"
        if "401" in error_msg or "Unauthorized" in error_msg:
            return False, "Неверный API ключ"
        if "429" in error_msg:
            return False, "Превышен лимит запросов"
        return False, error_msg[:50]


def get_custom_providers() -> list[str]:
    """Получает список custom провайдеров из .env."""
    env = load_existing_env()
    custom = env.get("ADVISOR_CUSTOM_PROVIDERS", "")
    return [p.strip() for p in custom.split(",") if p.strip()]


def setup_from_env() -> bool:
    """Setup from environment variables (non-interactive mode)."""
    env_vars: dict[str, str] = {}
    enabled_providers = []

    # Check for API keys in environment
    for provider_id, info in PROVIDER_INFO.items():
        env_key = info["env_key"]
        value = os.environ.get(env_key)
        if value:
            env_vars[env_key] = value
            enabled_providers.append(provider_id)

    if not enabled_providers:
        return False

    # Set defaults
    first_provider = enabled_providers[0]
    default_model = PROVIDER_INFO[first_provider]["models"][0]
    env_vars["ADVISOR_DEFAULT_MODEL"] = default_model

    # Compare models: one from each provider
    compare_models = []
    for provider_id in enabled_providers[:3]:  # Max 3 for compare
        compare_models.append(PROVIDER_INFO[provider_id]["models"][0])
    env_vars["ADVISOR_DEFAULT_MODELS_COMPARE"] = ",".join(compare_models)

    # Default options
    env_vars["ADVISOR_CACHE_ENABLED"] = "true"
    env_vars["ADVISOR_CACHE_TTL"] = "3600"
    env_vars["ADVISOR_VERBOSE"] = "false"

    # Merge with existing
    existing = load_existing_env()
    existing.update(env_vars)
    save_env(existing)

    return True


def input_custom_model(enabled_providers: list[str]) -> str | None:
    """Ввод и проверка произвольной модели."""
    console.print(
        "\n[dim]Примеры: gemini/gemini-2.5-pro, openai/gpt-4-turbo, groq/llama-3.3-70b[/dim]"
    )

    model = questionary.text(
        "Введите модель (provider/model):",
        style=WIZARD_STYLE,
        validate=lambda x: "/" in x or "Формат: provider/model",
    ).ask()

    if not model:
        return None

    # Проверка провайдера
    provider = model.split("/")[0]
    custom_providers = get_custom_providers()
    all_providers = enabled_providers + custom_providers

    if provider not in all_providers and provider not in PROVIDER_INFO:
        console.print(
            f"[yellow]Провайдер '{provider}' не настроен.[/yellow]\n"
            f"[dim]Настроенные: {', '.join(all_providers)}[/dim]"
        )
        proceed = questionary.confirm(
            "Продолжить?",
            default=False,
            style=WIZARD_STYLE,
        ).ask()
        if not proceed:
            return None

    # Тест модели
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
        transient=True,
    ) as progress:
        progress.add_task(description="Проверка модели...", total=None)
        success, msg = asyncio.run(test_model(model))

    if success:
        console.print(f"[green]✓ Модель {model} доступна[/green]")
        return model
    else:
        console.print(f"[red]✗ {msg}[/red]")
        retry = questionary.confirm(
            "Сохранить без проверки?",
            default=False,
            style=WIZARD_STYLE,
        ).ask()
        return model if retry else None


def select_providers(existing_env: dict[str, str]) -> list[str]:
    """Выбор провайдеров через checkbox."""
    choices = []
    for provider_id, info in PROVIDER_INFO.items():
        is_configured = bool(existing_env.get(info["env_key"]))
        label = info["name"]
        if is_configured:
            label += " (настроен)"
        choices.append(questionary.Choice(title=label, value=provider_id))

    selected = questionary.checkbox(
        "Выберите провайдеров для настройки:",
        choices=choices,
        style=WIZARD_STYLE,
        instruction="(Space - выбрать, Enter - подтвердить)",
    ).ask()

    return selected or []


def collect_api_key(provider: str, existing_value: str = "") -> str:
    """Собирает API ключ для провайдера."""
    info = PROVIDER_INFO[provider]
    console.print(f"\n[bold cyan]{info['name']}[/bold cyan]")
    console.print(f"[dim]Получить ключ: {info['url']}[/dim]")

    if existing_value:
        masked = (
            existing_value[:4] + "*" * (len(existing_value) - 8) + existing_value[-4:]
        )
        console.print(f"[dim]Текущий ключ: {masked}[/dim]")

    default = info.get("default_value", "")
    prompt_text = f"API ключ{' (Enter для текущего)' if existing_value else ''}: "

    key = questionary.password(
        prompt_text,
        style=WIZARD_STYLE,
    ).ask()

    if not key and existing_value:
        return existing_value
    if not key and default:
        return default

    return key or ""


CUSTOM_MODEL_OPTION = "[Ввести свою модель]"


def select_default_model(enabled_providers: list[str]) -> str:
    """Выбор модели по умолчанию."""
    choices = []
    for provider_id in enabled_providers:
        info = PROVIDER_INFO.get(provider_id, {})
        for model in info.get("models", []):
            choices.append(model)

    # Добавляем опцию ввода произвольной модели
    choices.append(CUSTOM_MODEL_OPTION)

    if len(choices) == 1:
        # Только опция "Ввести свою модель"
        return input_custom_model(enabled_providers) or "gemini/gemini-2.0-flash"

    selected = questionary.select(
        "Модель по умолчанию:",
        choices=choices,
        style=WIZARD_STYLE,
    ).ask()

    if selected == CUSTOM_MODEL_OPTION:
        custom = input_custom_model(enabled_providers)
        return custom or choices[0]

    return selected or choices[0]


def select_compare_models(enabled_providers: list[str], default_model: str) -> str:
    """Выбор моделей для сравнения."""
    choices = []
    for provider_id in enabled_providers:
        info = PROVIDER_INFO.get(provider_id, {})
        for model in info.get("models", []):
            choices.append(
                questionary.Choice(
                    title=model,
                    value=model,
                    checked=(model != default_model),
                )
            )

    # Добавляем опцию ввода произвольной модели
    choices.append(
        questionary.Choice(title=CUSTOM_MODEL_OPTION, value=CUSTOM_MODEL_OPTION)
    )

    if len(choices) == 1:
        return default_model

    selected = questionary.checkbox(
        "Модели для сравнения (advisor_compare_experts):",
        choices=choices,
        style=WIZARD_STYLE,
        instruction="(Space - выбрать, Enter - подтвердить)",
    ).ask()

    if not selected:
        return default_model

    # Обработка выбора произвольной модели
    result_models = []
    for model in selected:
        if model == CUSTOM_MODEL_OPTION:
            custom = input_custom_model(enabled_providers)
            if custom:
                result_models.append(custom)
        else:
            result_models.append(model)

    return ",".join(result_models) if result_models else default_model


def configure_options(existing_env: dict[str, str]) -> dict[str, str]:
    """Настройка дополнительных опций."""
    options = {}

    # Кэширование
    cache_enabled = questionary.confirm(
        "Включить кэширование ответов?",
        default=existing_env.get("ADVISOR_CACHE_ENABLED", "true").lower() == "true",
        style=WIZARD_STYLE,
    ).ask()

    options["ADVISOR_CACHE_ENABLED"] = "true" if cache_enabled else "false"

    if cache_enabled:
        cache_ttl = questionary.text(
            "TTL кэша в секундах:",
            default=existing_env.get("ADVISOR_CACHE_TTL", "3600"),
            style=WIZARD_STYLE,
        ).ask()
        options["ADVISOR_CACHE_TTL"] = cache_ttl or "3600"

    # Verbose логирование
    verbose = questionary.confirm(
        "Включить подробное логирование?",
        default=existing_env.get("ADVISOR_VERBOSE", "false").lower() == "true",
        style=WIZARD_STYLE,
    ).ask()

    options["ADVISOR_VERBOSE"] = "true" if verbose else "false"

    return options


def run_setup(
    non_interactive: bool = False,
    providers: list[str] | None = None,
    model: str | None = None,
):
    """Главная функция wizard'а.

    Args:
        non_interactive: If True, use defaults and env vars without prompts
        providers: List of provider IDs to configure (for -y mode)
        model: Default model to set (for -y mode)
    """
    if non_interactive:
        success = setup_from_env()
        if success:
            console.print(
                "[green]✓ Конфигурация создана из переменных окружения[/green]"
            )
        else:
            console.print("[red]✗ Не найдены API ключи в окружении[/red]")
            console.print("[dim]Установите GEMINI_API_KEY, OPENAI_API_KEY и т.д.[/dim]")
        return

    console.print(
        Panel(
            "[bold cyan]MCP Advisor — Настройка[/bold cyan]\n\n"
            "Этот wizard поможет настроить подключение к LLM провайдерам.",
            border_style="cyan",
        )
    )

    # Загружаем существующую конфигурацию
    existing_env = load_existing_env()
    new_env = dict(existing_env)

    # Шаг 1: Выбор провайдеров
    console.print("\n[bold]Шаг 1/4:[/bold] Выбор провайдеров\n")
    selected_providers = select_providers(existing_env)

    if not selected_providers:
        console.print("[yellow]Не выбрано ни одного провайдера. Выход.[/yellow]")
        return

    # Шаг 2: Сбор и проверка API ключей
    console.print("\n[bold]Шаг 2/4:[/bold] Настройка API ключей\n")
    enabled_providers = []

    for provider in selected_providers:
        info = PROVIDER_INFO[provider]
        env_key = info["env_key"]
        existing_key = existing_env.get(env_key, "")

        api_key = collect_api_key(provider, existing_key)

        if not api_key:
            console.print(f"[yellow]Пропущен {info['name']}[/yellow]")
            continue

        # Тестируем подключение
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
            transient=True,
        ) as progress:
            progress.add_task(description="Проверка подключения...", total=None)
            success, message = asyncio.run(test_connection(provider, api_key))

        if success:
            console.print("[green]Подключение успешно[/green]")
            new_env[env_key] = api_key
            enabled_providers.append(provider)

            # Дополнительные переменные окружения
            if "extra_env" in info:
                for k, v in info["extra_env"].items():
                    new_env[k] = v
        else:
            console.print(f"[red]Ошибка: {message}[/red]")
            retry = questionary.confirm(
                "Сохранить ключ без проверки?",
                default=False,
                style=WIZARD_STYLE,
            ).ask()

            if retry:
                new_env[env_key] = api_key
                enabled_providers.append(provider)

    if not enabled_providers:
        console.print("[yellow]Не настроен ни один провайдер. Выход.[/yellow]")
        return

    # Шаг 3: Выбор моделей
    console.print("\n[bold]Шаг 3/4:[/bold] Выбор моделей\n")

    default_model = select_default_model(enabled_providers)
    new_env["ADVISOR_DEFAULT_MODEL"] = default_model

    compare_models = select_compare_models(enabled_providers, default_model)
    new_env["ADVISOR_DEFAULT_MODELS_COMPARE"] = compare_models

    # Шаг 4: Дополнительные настройки
    console.print("\n[bold]Шаг 4/4:[/bold] Дополнительные настройки\n")

    options = configure_options(existing_env)
    new_env.update(options)

    # Сохранение
    save_env(new_env)

    console.print(
        Panel(
            f"[bold green]Конфигурация сохранена в {ENV_FILE}[/bold green]\n\n"
            f"Включённые провайдеры: {', '.join(enabled_providers)}\n"
            f"Модель по умолчанию: {default_model}",
            border_style="green",
        )
    )


if __name__ == "__main__":
    run_setup()
